# Generated by Django 5.2.11 on 2026-02-07 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_activity_attachment_checklist_checklistitem_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='card',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('VIEWER', 'VIEWER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
