# Generated by Django 5.0.6 on 2026-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_triggered_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.AddField(
            model_name='card',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
