# Generated by Django 5.0.6 on 2026-02-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_comment_options_card_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_brightness',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='board',
            name='background_type',
            field=models.CharField(choices=[('color', 'Solid Color'), ('gradient', 'Gradient'), ('photo', 'Photo')], default='color', max_length=20),
        ),
        migrations.AddField(
            model_name='board',
            name='background_value',
            field=models.TextField(default='#0079BF'),
        ),
    ]
