# Generated by Django 5.0.6 on 2026-02-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_board_background_brightness_board_background_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='action',
        ),
        migrations.AddField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('card_created', 'Card Created'), ('card_updated', 'Card Updated'), ('card_moved', 'Card Moved'), ('card_deleted', 'Card Deleted'), ('list_created', 'List Created'), ('list_updated', 'List Updated'), ('list_deleted', 'List Deleted'), ('comment_added', 'Comment Added'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('attachment_added', 'Attachment Added')], default='card_updated', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.list'),
        ),
        migrations.AddField(
            model_name='activity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activity',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.card'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-created_at'], name='crm_activit_created_f26fce_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['board', '-created_at'], name='crm_activit_board_i_7998f4_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['action_type', '-created_at'], name='crm_activit_action__b00b5a_idx'),
        ),
    ]
