# Generated by Django 5.0.6 on 2026-02-12 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_activity_options_remove_activity_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('card_created', 'Card Created'), ('card_updated', 'Card Updated'), ('card_moved', 'Card Moved'), ('card_deleted', 'Card Deleted'), ('card_archived', 'Card Archived'), ('card_restored', 'Card Restored'), ('list_created', 'List Created'), ('list_updated', 'List Updated'), ('list_deleted', 'List Deleted'), ('comment_added', 'Comment Added'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('attachment_added', 'Attachment Added')], default='card_updated', max_length=50),
        ),
    ]
