# Generated by Django 5.0.6 on 2026-02-18 14:34 (modified to add deduplication)

from django.db import migrations


def deduplicate_labels(apps, schema_editor):
    """
    Before making (name, color) unique globally, merge duplicate labels.
    For each group of labels with the same name+color, keep the first one
    and re-point all card M2M references to it, then delete the duplicates.
    """
    Label = apps.get_model('crm', 'Label')
    Card = apps.get_model('crm', 'Card')

    seen = {}  # (name, color) -> canonical Label id

    for label in Label.objects.order_by('id'):
        key = (label.name, label.color)
        if key not in seen:
            seen[key] = label.id
        else:
            # This is a duplicate — re-point all cards using this label to the canonical one
            canonical_id = seen[key]
            canonical = Label.objects.get(id=canonical_id)
            for card in label.cards.all():
                card.labels.remove(label)
                card.labels.add(canonical)
            label.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_workspacemember'),
    ]

    operations = [
        # Step 1: deduplicate existing labels before adding the unique constraint
        migrations.RunPython(deduplicate_labels, migrations.RunPython.noop),
        # Step 2: apply the new global unique_together
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'color')},
        ),
        # Step 3: drop the board FK
        migrations.RemoveField(
            model_name='label',
            name='board',
        ),
    ]
