# Generated by Django 5.0.6 on 2026-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_label_global_remove_board_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('card_created', 'Card Created'), ('card_updated', 'Card Updated'), ('card_moved', 'Card Moved'), ('card_deleted', 'Card Deleted'), ('card_archived', 'Card Archived'), ('card_restored', 'Card Restored'), ('list_created', 'List Created'), ('list_updated', 'List Updated'), ('list_deleted', 'List Deleted'), ('comment_added', 'Comment Added'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('due_date_set', 'Due Date Set'), ('due_date_changed', 'Due Date Changed'), ('attachment_added', 'Attachment Added'), ('checklist_item_completed', 'Checklist Item Completed')], default='card_updated', max_length=50),
        ),
    ]
