# Generated by Django 5.2.15 on 2026-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_activity_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
